// <auto-generated />
using System;
using ByteGuard.Codex.Infrastructure.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByteGuard.Codex.Infrastructure.Sqlite.Migrations
{
    [DbContext(typeof(CodexDbContext))]
    [Migration("20251203061742_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsvsVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsvsVersionId");

                    b.ToTable("AsvsChapters");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsvsSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsvsSectionId");

                    b.ToTable("AsvsRequirements");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsvsChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsvsChapterId");

                    b.ToTable("AsvsSections");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AsvsVersions");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsvsVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsvsVersionId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.ProjectRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsvsRequirementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsvsRequirementId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRequirements");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsChapter", b =>
                {
                    b.HasOne("ByteGuard.Codex.Core.Entities.AsvsVersion", "AsvsVersion")
                        .WithMany("AsvsChapters")
                        .HasForeignKey("AsvsVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsvsVersion");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsRequirement", b =>
                {
                    b.HasOne("ByteGuard.Codex.Core.Entities.AsvsSection", "AsvsSection")
                        .WithMany("AsvsRequirements")
                        .HasForeignKey("AsvsSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsvsSection");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsSection", b =>
                {
                    b.HasOne("ByteGuard.Codex.Core.Entities.AsvsChapter", "AsvsChapter")
                        .WithMany("AsvsSections")
                        .HasForeignKey("AsvsChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsvsChapter");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.Project", b =>
                {
                    b.HasOne("ByteGuard.Codex.Core.Entities.AsvsVersion", "AsvsVersion")
                        .WithMany()
                        .HasForeignKey("AsvsVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsvsVersion");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.ProjectRequirement", b =>
                {
                    b.HasOne("ByteGuard.Codex.Core.Entities.AsvsRequirement", "AsvsRequirement")
                        .WithMany()
                        .HasForeignKey("AsvsRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteGuard.Codex.Core.Entities.Project", null)
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AsvsRequirement");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsChapter", b =>
                {
                    b.Navigation("AsvsSections");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsSection", b =>
                {
                    b.Navigation("AsvsRequirements");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.AsvsVersion", b =>
                {
                    b.Navigation("AsvsChapters");
                });

            modelBuilder.Entity("ByteGuard.Codex.Core.Entities.Project", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
